deployment:
  tasks:
    # Synchronize files using rsync
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.htaccess' --exclude='node_modules/' $HOME/repositories/billDivider/ $HOME/billdivider.fun/
