deployment:
  tasks:
    - export DEPLOYPATH=/home/coolappl/billdivider.fun/
    - find $DEPLOYPATH -type f -name "*.js" -delete
    - find $DEPLOYPATH -type f -name "*.css" -delete
    - find $DEPLOYPATH -type f -name "*.txt" -delete
    - /bin/cp -R * $DEPLOYPATH
