name: Deploy to cPanel

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Deploy to cPanel
      run: |
        export DEPLOYPATH=/home/coolappl/repositories/billDivider-staging
        /usr/local/cpanel/3rdparty/bin/git pull origin staging
        /usr/local/cpanel/3rdparty/bin/git submodule update --init --recursive
        if [[ $(git log -1 --pretty=%B) =~ "merge" ]]; then
          export MAIN_DEPLOYPATH=/home/coolappl/repositories/billDivider
          /usr/local/cpanel/3rdparty/bin/git pull origin main
          /usr/local/cpanel/3rdparty/bin/git submodule update --init --recursive
        fi
